import numpy as np


class UltimateTicTacToe:
    SYMM_AUG_INDICES_3x3 = [
        [0, 1, 2, 3, 4, 5, 6, 7, 8],  # identity
        [2, 5, 8, 1, 4, 7, 0, 3, 6],  # rot 90 CCW
        [8, 7, 6, 5, 4, 3, 2, 1, 0],  # rot 180
        [6, 3, 0, 7, 4, 1, 8, 5, 2],  # rot 270 CCW
        [2, 1, 0, 5, 4, 3, 8, 7, 6],  # flip horizontal
        [6, 7, 8, 3, 4, 5, 0, 1, 2],  # flip vertical
        [0, 3, 6, 1, 4, 7, 2, 5, 8],  # transpose (main diag)
        [8, 5, 2, 7, 4, 1, 6, 3, 0],  # anti-transpose
    ]

    SYMM_AUG_INDICES_9x9 = [
        [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
        ],
        [
            20,
            23,
            26,
            19,
            22,
            25,
            18,
            21,
            24,
            47,
            50,
            53,
            46,
            49,
            52,
            45,
            48,
            51,
            74,
            77,
            80,
            73,
            76,
            79,
            72,
            75,
            78,
            11,
            14,
            17,
            10,
            13,
            16,
            9,
            12,
            15,
            38,
            41,
            44,
            37,
            40,
            43,
            36,
            39,
            42,
            65,
            68,
            71,
            64,
            67,
            70,
            63,
            66,
            69,
            2,
            5,
            8,
            1,
            4,
            7,
            0,
            3,
            6,
            29,
            32,
            35,
            28,
            31,
            34,
            27,
            30,
            33,
            56,
            59,
            62,
            55,
            58,
            61,
            54,
            57,
            60,
        ],
        [
            80,
            79,
            78,
            77,
            76,
            75,
            74,
            73,
            72,
            71,
            70,
            69,
            68,
            67,
            66,
            65,
            64,
            63,
            62,
            61,
            60,
            59,
            58,
            57,
            56,
            55,
            54,
            53,
            52,
            51,
            50,
            49,
            48,
            47,
            46,
            45,
            44,
            43,
            42,
            41,
            40,
            39,
            38,
            37,
            36,
            35,
            34,
            33,
            32,
            31,
            30,
            29,
            28,
            27,
            26,
            25,
            24,
            23,
            22,
            21,
            20,
            19,
            18,
            17,
            16,
            15,
            14,
            13,
            12,
            11,
            10,
            9,
            8,
            7,
            6,
            5,
            4,
            3,
            2,
            1,
            0,
        ],
        [
            60,
            57,
            54,
            61,
            58,
            55,
            62,
            59,
            56,
            33,
            30,
            27,
            34,
            31,
            28,
            35,
            32,
            29,
            6,
            3,
            0,
            7,
            4,
            1,
            8,
            5,
            2,
            69,
            66,
            63,
            70,
            67,
            64,
            71,
            68,
            65,
            42,
            39,
            36,
            43,
            40,
            37,
            44,
            41,
            38,
            15,
            12,
            9,
            16,
            13,
            10,
            17,
            14,
            11,
            78,
            75,
            72,
            79,
            76,
            73,
            80,
            77,
            74,
            51,
            48,
            45,
            52,
            49,
            46,
            53,
            50,
            47,
            24,
            21,
            18,
            25,
            22,
            19,
            26,
            23,
            20,
        ],
        [
            20,
            19,
            18,
            23,
            22,
            21,
            26,
            25,
            24,
            11,
            10,
            9,
            14,
            13,
            12,
            17,
            16,
            15,
            2,
            1,
            0,
            5,
            4,
            3,
            8,
            7,
            6,
            47,
            46,
            45,
            50,
            49,
            48,
            53,
            52,
            51,
            38,
            37,
            36,
            41,
            40,
            39,
            44,
            43,
            42,
            29,
            28,
            27,
            32,
            31,
            30,
            35,
            34,
            33,
            74,
            73,
            72,
            77,
            76,
            75,
            80,
            79,
            78,
            65,
            64,
            63,
            68,
            67,
            66,
            71,
            70,
            69,
            56,
            55,
            54,
            59,
            58,
            57,
            62,
            61,
            60,
        ],
        [
            60,
            61,
            62,
            57,
            58,
            59,
            54,
            55,
            56,
            69,
            70,
            71,
            66,
            67,
            68,
            63,
            64,
            65,
            78,
            79,
            80,
            75,
            76,
            77,
            72,
            73,
            74,
            33,
            34,
            35,
            30,
            31,
            32,
            27,
            28,
            29,
            42,
            43,
            44,
            39,
            40,
            41,
            36,
            37,
            38,
            51,
            52,
            53,
            48,
            49,
            50,
            45,
            46,
            47,
            6,
            7,
            8,
            3,
            4,
            5,
            0,
            1,
            2,
            15,
            16,
            17,
            12,
            13,
            14,
            9,
            10,
            11,
            24,
            25,
            26,
            21,
            22,
            23,
            18,
            19,
            20,
        ],
        [
            0,
            3,
            6,
            1,
            4,
            7,
            2,
            5,
            8,
            27,
            30,
            33,
            28,
            31,
            34,
            29,
            32,
            35,
            54,
            57,
            60,
            55,
            58,
            61,
            56,
            59,
            62,
            9,
            12,
            15,
            10,
            13,
            16,
            11,
            14,
            17,
            36,
            39,
            42,
            37,
            40,
            43,
            38,
            41,
            44,
            63,
            66,
            69,
            64,
            67,
            70,
            65,
            68,
            71,
            18,
            21,
            24,
            19,
            22,
            25,
            20,
            23,
            26,
            45,
            48,
            51,
            46,
            49,
            52,
            47,
            50,
            53,
            72,
            75,
            78,
            73,
            76,
            79,
            74,
            77,
            80,
        ],
        [
            80,
            77,
            74,
            79,
            76,
            73,
            78,
            75,
            72,
            53,
            50,
            47,
            52,
            49,
            46,
            51,
            48,
            45,
            26,
            23,
            20,
            25,
            22,
            19,
            24,
            21,
            18,
            71,
            68,
            65,
            70,
            67,
            64,
            69,
            66,
            63,
            44,
            41,
            38,
            43,
            40,
            37,
            42,
            39,
            36,
            17,
            14,
            11,
            16,
            13,
            10,
            15,
            12,
            9,
            62,
            59,
            56,
            61,
            58,
            55,
            60,
            57,
            54,
            35,
            32,
            29,
            34,
            31,
            28,
            33,
            30,
            27,
            8,
            5,
            2,
            7,
            4,
            1,
            6,
            3,
            0,
        ],
    ]

    WIN_LINES = (
        (0, 1, 2),
        (3, 4, 5),
        (6, 7, 8),  # rows
        (0, 3, 6),
        (1, 4, 7),
        (2, 5, 8),  # cols
        (0, 4, 8),
        (2, 4, 6),  # diags
    )

    @staticmethod
    def get_init_state():
        return {
            "board": np.zeros((9, 9), dtype=np.int8),
            "active": np.ones(9, dtype=bool),
        }

    @staticmethod
    def get_next_state(state, player, action):
        b, c = action // 9, action % 9
        board = state["board"].copy()
        board[b, c] = player
        meta_board = UltimateTicTacToe._derive_meta_board(board)
        # The cell played (c) determines which macro board the opponent must play in.
        if meta_board[c] != 0:
            # Target board is already decided — opponent may play in any open board.
            active = meta_board == 0
        else:
            active = np.zeros(9, dtype=bool)
            active[c] = True
        return {"board": board, "active": active}, -player

    @staticmethod
    def get_valid_moves(state, player=1):
        # Valid if the board is active and the cell is empty.
        valid = np.zeros(81, dtype=np.int8)
        for b in np.argwhere(state["active"]).reshape(-1):
            valid[b * 9 : (b + 1) * 9] = state["board"][b] == 0
        return valid

    @staticmethod
    def get_game_ended(state, player):
        meta_board = UltimateTicTacToe._derive_meta_board(state["board"])
        winner = UltimateTicTacToe._get_board_winner(meta_board)
        if winner == player:
            return 1.0
        if winner == -player:
            return -1.0
        if winner == 2:
            # 1e-4 not 0.0: in Python 0.0 == 0 is True, so returning 0.0 for draw
            # makes it indistinguishable from ongoing (0) under any `if r != 0` check.
            return 1e-4
        return 0

    @staticmethod
    def get_canonical_form(state, player):
        return {
            "board": state["board"] * player,
            "active": state["active"],
        }

    @staticmethod
    def get_symmetries(state, pi):
        board = state["board"]
        active = state["active"]

        result = []
        for idx9, idx3 in zip(
            UltimateTicTacToe.SYMM_AUG_INDICES_9x9,
            UltimateTicTacToe.SYMM_AUG_INDICES_3x3,
            strict=True,
        ):
            new_board = board.reshape(-1)[idx9].reshape(9, 9)
            new_active = active[idx3]
            new_pi = pi[idx9]
            result.append(({"board": new_board, "active": new_active}, new_pi))
        return result

    @staticmethod
    def get_string_representation(state):
        return state["board"].tobytes() + state["active"].tobytes()

    @staticmethod
    def _get_board_winner(board):
        for a, b, c in UltimateTicTacToe.WIN_LINES:
            if board[a] == board[b] == board[c] == 1:
                return 1
            if board[a] == board[b] == board[c] == -1:
                return -1
        return 2 if all(x != 0 for x in board) else 0

    @staticmethod
    def _derive_meta_board(board):
        meta = np.empty(9, dtype=np.int8)
        for i in range(9):
            meta[i] = UltimateTicTacToe._get_board_winner(board[i])
        return meta
